!obj:pylearn2.train.Train {
    dataset: &train !pkl: "train.pkl",
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [ !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 200,
                     sparse_init: 5
                 },  !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h1',
                     dim: 200,
                     sparse_init: 5
                 }, !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 9,
                     irange: 0.
                 }
                ],
        nvis: 93,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 100,
        learning_rate: 0.1,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !pkl: "val.pkl",
                'test'  : !pkl: "test.pkl"
            },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
                default_input_include_prob: 0.5,
                default_input_scale: 2.0
        },
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 10
                }
            ]
        }
    },
    save_freq : 1
}
